#docker required super admin (sudo) permissions
sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sosnovskiserge/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sosnovskiserge/docker-react npm run test
